version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/task-db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
