version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/task-db
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
